INSERT INTO INSCHRIJVINGEN (CURSIST, CURSUS, BEGINDATUM)
VALUES (7900, 'JAV', TO_DATE('01-02-2000', 'DD-MM-YYYY'));


-- Insert
INSERT INTO CURSUSSEN
VALUES ('ADP', 'Adaptive Programming', 'ALG', 1);
INSERT INTO UITVOERINGEN
VALUES ('ADP', TO_DATE('16-04-2019', 'DD-MM-YYYY'), 7566, 'UTRECHT');
INSERT INTO INSCHRIJVINGEN (CURSIST, CURSUS, BEGINDATUM)
VALUES (7900, 'ADP', TO_DATE('16-04-2019', 'DD-MM-YYYY'));

-- Select
SELECT CURSUS FROM INSCHRIJVINGEN;

-- Update
UPDATE INSCHRIJVINGEN
SET EVALUATIE = 4
WHERE CURSIST = 7900;

-- Delete
DELETE FROM INSCHRIJVINGEN
WHERE EVALUATIE < 3;